# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6d115e80e3820eab3f54bd3b9c8f55a2f07a862d184f8d2fdf6228d82811c92e6a45ea35082b4bbc026b55cc3fbdc8e72a546102578d3d45bbdc4d95af66d2c

test:
  secret_key_base: 44a00b3ee7da7dc58630363c962635b382add87ff3a9e4d5789946fc1402c0f0eeaf866354d1ff9e6838620c6123eda675c69a3c348ec3710371d34be20516bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
